[workspace]
members = [
    # "clients/*",
    "programs/*",
    "tests",
]
resolver = "2"

[workspace.package]
version = "0.1.0"
edition = "2021"

[workspace.dependencies]
litesvm = "0.8.2"
pinocchio = "0.9.2"
pinocchio_counter = { path = "programs/pinocchio_counter" }
solana-keypair = "~3.0"
